/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.59
 * Generated at: 2015-07-29 13:55:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.apache.jasper.tagplugins.jstl.core.ForEach;
import java.util.ArrayList;
import model.object.*;
import servlet.*;

public final class ObjectSample_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/contents/Search.jsp", Long.valueOf(1438178104710L));
    _jspx_dependants.put("/WEB-INF/contents/InputBox.jsp", Long.valueOf(1438092511473L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta http-equiv=\"Content-Script-Type\" content=\"text/javascript\">\r\n");
      out.write("    <script type=\"text/javascript\" src=\"./resources/js/jquery-2.1.4.min.js\" charset=\"UTF-8\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"./resources/js/ObjectSample.js\" charset=\"UTF-8\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"./resources/js/InputBox.js\" charset=\"UTF-8\"></script>\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"./resources/css/ObjectSample.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"./resources/css/InputBox.css\">\r\n");
      out.write("\t<title>ObjectSample</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"contents\">\r\n");
      out.write("    <div id=\"leftSide\">\r\n");
      out.write("\t<h1>ProfileObject</h1>\r\n");
      out.write("\t<br/>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<div id =\"inputBox\">\r\n");
      out.write("<form method=\"post\" action=\"ObjectSampleServlet\" autocomplete=\"off\">\r\n");
      out.write("\t<table border=\"1\">\r\n");
      out.write("\t<tr class=\"name\">\r\n");
      out.write("\t\t<td>名前</td>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<input type=\"text\" name=\"name\" size=\"30\"onchange=\"showFukidasi(this.form, 'name', ['name',]);\" onKeyUp=\"showFukidasi(this.form, 'name', ['name',]);\">\r\n");
      out.write("\t\t\t<span class=\"fukidasipop\">ProfileObject.名前 = <span id=\"name\"></span></span>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr class=\"birthDay\">\r\n");
      out.write("\t\t<td>誕生日</td>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<input type=\"date\" name=\"birthDay\"onchange=\"showFukidasi(this.form, 'birthDay', ['birthDay',]);\">\r\n");
      out.write("\t\t\t<span class=\"fukidasipop\">ProfileObject.誕生日 = <span id=\"birthDay\"></span></span>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr class=\"old\">\r\n");
      out.write("\t\t<td>年齢</td>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<input type=\"number\" name=\"old\" max=\"99\" min=\"0\"onchange=\"showFukidasi(this.form, 'old', ['old',]);\"onKeyUp=\"showFukidasi(this.form, 'old', ['old',]);\">\r\n");
      out.write("\t\t\t<span class=\"fukidasipop\">ProfileObject.年齢 = <span id=\"old\"></span></span>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<input type=\"submit\" value=\"送信\" name=\"sendBtn\">\r\n");
      out.write("</form>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<button id=\"addButton\" onclick=\"openBox()\">追加</button>\r\n");
      out.write("\t<br/>\r\n");
      out.write("\t");

		ArrayList<ProfileObject> poList = (ArrayList<ProfileObject>)request.getAttribute("requetPoList") ;
		if(poList != null){
			for(ProfileObject po : poList){
				out.println("<br/>");
				out.println("<table border='1'>");
				out.println("<tr>");
				out.println("<td>名前</td>" + "<td>" + po.getName() + "</td>");
				out.println("</tr>");

				out.println("<tr>");
				out.println("<td>誕生日</td>" + "<td>" + po.getBirthDay() + "</td>");
				out.println("</tr>");

				out.println("<tr>");
				out.println("<td>年齢</td>" + "<td>" + po.getOld() + "</td>");
				out.println("</tr>");

				out.println("</table>");
			}
		}
	
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"rightSide\">\r\n");
      out.write("    <h1>検索</h1>\r\n");
      out.write("    <br/>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<form method=\"post\" action=\"ObjectSampleServlet\" autocomplete=\"off\">\r\n");
      out.write("<div class=\"searchFukidasi\">\r\n");
      out.write("\t<table>\r\n");
      out.write("\t\t<tr class=\"searchWord\">\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<select name=\"selectProperty\"onchange=\"showFukidasi(this.form, 'searchFukidasi', ['searchWord','selectProperty']);\">\r\n");
      out.write("\t\t\t\t\t<option value=\"名前\">名前</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"誕生日\">誕生日</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"年齢\">年齢</option>\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"searchWord\" size=\"30\"onchange=\"showFukidasi(this.form, 'searchFukidasi', ['searchWord','selectProperty ']);\"onKeyUp=\"showFukidasi(this.form, 'searchFukidasi', ['searchWord','selectProperty']);\"/>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<input type=\"submit\" value=\"検索\" name=\"searchBtn\">\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<span class=\"fukidasipop\">検索(ProfileObject.<span id=\"selectProperty\"></span> == <span id=\"searchWord\"></span>)</span>\r\n");
      out.write("</div>\r\n");
      out.write("</form>");
      out.write('\r');
      out.write('\n');
      out.write('	');

		ArrayList<ProfileObject> searchResultList = (ArrayList<ProfileObject>)request.getAttribute("searchResultList") ;
		if(searchResultList != null){
			for(ProfileObject po : searchResultList){
				out.println("<br/>");
				out.println("<table border='1'>");
				out.println("<tr>");
				out.println("<td>名前</td>" + "<td>" + po.getName() + "</td>");
				out.println("</tr>");

				out.println("<tr>");
				out.println("<td>誕生日</td>" + "<td>" + po.getBirthDay() + "</td>");
				out.println("</tr>");

				out.println("<tr>");
				out.println("<td>年齢</td>" + "<td>" + po.getOld() + "</td>");
				out.println("</tr>");

				out.println("</table>");
			}
		}
	
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
